### PR TITLE
Creating a PR request for my FitTube v1.0

### PR DESCRIPTION
**Pull request by sdhamani**
Hello Everyone,

This is version one of my video library FitTube.

Website is deployed on - https://fittube.netlify.app/

Tech Stach -

Frontend - I used react JS for JS library, CSS for styling, and context API for state management, and react-router v-6 for routing.

Features -

Responsive Landing page with carousel 
Features including add to playlist, like video,  add to watch later. Played video gets added to the history list.
Playlist management to remove a video from it and playlist gets deleted once there are no videos in it.

Please go through the site and I would be happy to know your feedback as that would help me to become a good developer.

Thanks & Regards,
Sagar Dhamani

### CODE REVIEW

**Comment by OmkarArora** [comment]
Really nice layout, the carousel is also good. Here are some things I noticed - 
1. In the side-navbar, the cursor:pointer only works for icons and not the text, you can add it to text as well.
2. The search bar doesn't seem to update results when backspace is pressed.
3. The app logo gets misaligned on some screen sizes like iPad screens. I'm not sure if this behavior is intended
image

Code -
1. App.css is currently empty, you can delete it and remove the import from App.js if you don't intend to add anything later.
2. Update the README according to your project details.

**Comment by Akshaay9** [comment]
Hey sagar, the website looks good, here are few of my suggestions,
1) When user clicks on search bar, try to Route search bar and whole search Items to some other screen so your Home screen remails clean, and does not affect your Carousal, its just a suggestion
2) On caroual css add
`.card-image-ecom {transition:all 250ms eas-in-out}`
to make it looks smooth
other than that everything looks great

**Comment by sdhamani** [comment]
> Really nice layout, the carousel is also good. Here are some things I noticed -
> 
> 1. In the side-navbar, the cursor: pointer only works for icons and not the text, you can add it to text as well.
> 2. The search bar doesn't seem to update results when backspace is pressed.
> 3. The app logo gets misaligned on some screen sizes like iPad screens. I'm not sure if this behavior is intended
>    image
> 
> Code -
> 
> 1. App.css is currently empty, you can delete it and remove the import from App.js if you don't intend to add anything later.
> 2. Update the README according to your project details.

Hi Omkar,
Thank You for reviewing my PR.

I have made the following changes- 
1. Now The sidebar cursor works on the text too.
2. The search bar update results when backspace is pressed.
3. I have made it responsive for desktop and mobile phones only.
4. Removed App.css file
5. Updated README of the repo.

Let me know if the changes are done properly.

**Comment by sdhamani** [comment]
> 2\. transition:all 250ms eas-in-out

Hi Akshay,
Thank You for the review.

I have made the changes which you asked for. The Carousal transition is so smooth and it looks really good. Thank you for that too.

**Comment by Akshaay9** [comment]
> > 2. transition:all 250ms eas-in-out
> 
> Hi Akshay,
> Thank You for the review.
> 
> I have made the changes which you asked for. The Carousal transition is so smooth and it looks really good. Thank you for that too.

Thanks for considering my suggestion and making changes accordingly, the website looks better now
you are good to go..!!

**Review by OmkarArora — APPROVED** [review]
Cross checked the changes and seems good to me.

**Comment by ishanjirety** [comment]
Hi Sagar, the site looks really nice also the code is clean.
One suggestion you should add a 404 page to the intimate user about the incorrect path.

Rest everything looks good.

**Comment by sdhamani** [comment]
> Hi Sagar, the site looks really nice also the code is clean.
> One suggestion you should add a 404 page to the intimate user about the incorrect path.
> 
> Rest everything looks good.


Hi Ishan,
Thanks a lot for reviewing my code.

I have added the 404 page.

Thanks & Regards,
Sagar Dhamani

**Pull request merged**
